### ISSUE TITLE
Permissioni denied(publickey)

### ISSUE THREAD

**Issue by cliviaK** [kerycdiaz/crypto-bot#1]
Hi,

I'm using AWS cloud, Ubuntu system
I'm trying to clone repository after I've done Docker and Docker Compose, when I copy the clone repository code,"git clone git@github.com:kerycdiaz/crypto-bot.git && cd crypto-bot", it shows "permission denied, plesae make sure you have the correct access rights"

I've attached a screenshot here, is there something I need to sign in? Thanks

![2022-02-06 08_24_44-2022_02_06_08_23_48_ubuntu_ip_172_31_91_61_ - Paint](https://user-images.githubusercontent.com/96049251/152659631-00bf6758-6bf2-49c8-a33e-334c694468cf.jpg)
.

**Comment by kerycdiaz** [comment]
I’m sorry, you can try using the http url please, `git clone https://github.com/kerycdiaz/crypto-bot.git`
