### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by Mikyner** [kerycdiaz/crypto-bot#6]
![image](https://user-images.githubusercontent.com/52259575/196742120-8f68c63b-4963-418c-9283-38234a2380b6.png)

**Comment by kerycdiaz** [comment]
You must run `docker-compose up` without sudo.

**Comment by kerycdiaz** [comment]
The problem is that there is no folder called `logs` inside `user_data`, you can create it manually.

I already made the correction so that it is always downloaded when cloning the project
